services:
  app:
    build: .
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./:/code
    depends_on:
      - rabbitmq
    tty: true
    stdin_open: true
  celery:
    build: .
    command: >
      sh -c "celery -A vcelerydev worker -l INFO"
    volumes:
      - ./:/code
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
